# Generated by Django 4.2.9 on 2024-02-17 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_delivery_parttimer"),
    ]

    operations = [
        migrations.AddField(
            model_name="delivery",
            name="partTimer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounts.parttimer",
            ),
        ),
        migrations.AddField(
            model_name="delivery",
            name="staff",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounts.staff",
            ),
        ),
    ]
